export const GET_CONVERSATION_REQUEST = 'GET_CONVERSATION_REQUEST';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_FAIL = 'GET_CONVERSATION_FAIL';
export const GET_CONVERSATION_RESET = 'GET_CONVERSATION_RESET';

export const MESSENGER_LIST_REQUEST = 'MESSENGER_LIST_REQUEST';
export const MESSENGER_LIST_SUCCESS = 'MESSENGER_LIST_SUCCESS';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const MESSENGER_LIST_FAIL = 'MESSENGER_LIST_FAIL';
export const MESSENGER_LIST_DELETE = 'MESSENGER_LIST_DELETE';
export const MESSENGER_LIST_RESET = 'MESSENGER_LIST_RESET';
